autoInstallPeers: false
dedupePeerDependents: false
engineStrict: true
enableGlobalVirtualStore: false
resolvePeersFromWorkspaceRoot: false
strictDepBuilds: true
strictStorePkgContentCheck: true
verifyDepsBeforeRun: error
verifyStoreIntegrity: true
dangerouslyAllowAllBuilds: false

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
